### ISSUE TITLE
Can't calculate minimum grade if higher than what it will be

### ISSUE THREAD

**Issue by EpicNeoGreg** [aopell/SchoologyPlus#93] opened 2018-12-05 05:51 UTC
Title, if an assignment that already has a point value is edited to calculate the minimum value for a grade, the value will not be lowered. For example, if I have a class with one 100 points assignment and I received a 100, if I pressed calculate minimum grade for A, it would not lower itself to 90 points and would remain at a 100. 

![image](https://user-images.githubusercontent.com/6147653/49492824-b71a8800-f80e-11e8-8f87-1dfd3d207706.png)

After clicking minimum grade for an A:

![image](https://user-images.githubusercontent.com/6147653/49492848-c699d100-f80e-11e8-8caa-1d1fe031bd35.png)

Thank you!

**Comment by glen3b** [comment] 2018-12-05 06:16
Thank you for reporting this issue.

This issue appears to be a duplicate of that found in ticket #91, which has been fixed in the development codebase for a while. I'm thus closing this issue as a duplicate; if you're interested you can follow that ticket, or if something distinguishes this issue from that one, differentiating details can be added here and we can reopen.

I just released a hotfix (v4.3.1) via normal addon distribution channels to fix #91. If you are still experiencing this issue on version 4.3.1, please leave a reply here with the relevant details and we can reopen this ticket to investigate further.

**Closed by glen3b** 2018-12-05 06:16 UTC
